config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'top/show'
  get 'users/show'
  devise_for :users
  resources :books do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  root 'books#index'
  patch 'notifications/admit' => 'rooms#admit' ,as:'room_admit'
  get 'notifications/deny'
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
    default_scope -> { order(created_at: :desc) }
    belongs_to :book, optional: true
    belongs_to :comment, optional: true
    belongs_to :message, optional: true
  
    belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    def index
        @notifications = current_user.passive_notifications.page(params[:page]).per(20)
        @notifications.where(checked: false).each do |notification|
          notification.update(checked: true)
        end 
    end
    def destroy
        @notifications = current_user.passive_notifications.destroy_all
        redirect_to notifications_path
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
    def notification_form(notification)
        @visitor = notification.visitor
        @comment = nil
        @message = nil
        your_book = link_to 'あなたの投稿', book_path(notification), style:"font-weight: bold;"
        @visitor_comment = notification.comment_id
        @visitor_message = notification.message_id
        #notification.actionがlikeかcommentかmessageか
        case notification.action
          when "like" then
            tag.a(notification.visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"が"+tag.a('あなたの出品', href:book_path(notification.book_id), style:"font-weight: bold;")+"に購入申請しました"
          when "comment" then
            @comment = Comment.find_by(id: @visitor_comment)
            tag.a(@visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:book_path(notification.book_id), style:"font-weight: bold;")+"にコメントしました"
          when "message" then
            @message = Message.find_by(id: @visitor_message)
            tag.a(@visitor.name, href:user_path(@visitor), style:"font-weight: bold;")+"が"+"あなたにDMを送りました。"
        end
    end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% book = notification.book %>
<div class="user-view clearfix">
    <%= link_to user_path(notification.visitor_id) do %>
    <% end %>
    <%= notification_form(notification) %>
      <span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
      <br>
      <% if !@comment.nil? %>
        <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @comment.comment %></p>
      <% elsif !@like.nil? %>
        <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @like.book_id %></p>
      <% elsif !@message.nil? %>
        <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @message.text %></p>
      <% end %>
      <hr>
</div>

app/views/notifications/index.html.erb
<%= stylesheet_link_tag 'notifications', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="text-center"><h1>通知</h1>
    <%= link_to notification_path(@notifications), method: :delete do %>
        <i class="fas fa-trash" style="color: black;"></i>
        <h7 style="color: black;">通知を削除する</h7>
    <% end %>
    <hr>
    <% if @notifications.exists? %>
        <div class="users-index">
            <%= render @notifications %>
        </div>
    <% else %>
        <p>通知はありません</p>
    <% end %>
</div>