config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'top/show'
  get 'users/show'
  devise_for :users
  resources :books do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  root 'books#index'
  patch 'notifications/admit' => 'rooms#admit' ,as:'room_admit'
  get 'notifications/deny'
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user 
    has_many :notifications, dependent: :destroy

    def create_notification_like!(current_user)
        # すでに「いいね」されているか検索
        temp = Notification.where(["visitor_id = ? and visited_id = ? and book_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
        # いいねされていない場合のみ、通知レコードを作成
        if temp.blank?
          notification = current_user.active_notifications.new(
            book_id: id,
            visited_id: user_id,
            action: 'like'
          )
          # 自分の投稿に対するいいねの場合は、通知済みとする
          if notification.visitor_id == notification.visited_id
            notification.checked = true
          end
          notification.save if notification.valid?
        end
    end

    def create_notification_comment!(current_user, comment_id)
        # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
        temp_ids = Comment.select(:user_id).where(book_id: id).where.not(user_id: current_user.id).distinct
        temp_ids.each do |temp_id|
          save_notification_comment!(current_user, comment_id, temp_id['user_id'])
        end
        # まだ誰もコメントしていない場合は、投稿者に通知を送る
        save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
      end
    
      def save_notification_comment!(current_user, comment_id, visited_id)
        # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
        notification = current_user.active_notifications.new(
          book_id: id,
          comment_id: comment_id,
          visited_id: visited_id,
          action: 'comment'
        )
        # 自分の投稿に対するコメントの場合は、通知済みとする
        if notification.visitor_id == notification.visited_id
          notification.checked = true
        end
        notification.save if notification.valid?
      end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    def index
        if params[:search] == nil
            @books = Book.all.page(params[:page]).per(15)
        elsif params[:search] == ''
            @books = Book.all.page(params[:page]).per(15)
        else
            @books = Book.where("title LIKE ?",'%' + params[:search] + '%').page(params[:page]).per(3)
        end 
    end
    def new
        @book = Book.new
    end
    def create
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end
    def show
        @book = Book.find(params[:id])
        @comments = @book.comments
        @comment = @book.comments.build
        @like = Like.new
    end
    def edit
        @book = Book.find(params[:id])
    end
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            redirect_to :action => "show", :id => @book.id
        else
            redirect_to :action => "new"
        end
    end
    def destroy
        Book.find(params[:id]).destroy
        redirect_to action: :index
    end
end

private
def book_params
    params.require(:book).permit(:title, :writer, :image, :classroom, :price, :user_id)
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>
 
    <div class="edit-container">
        <%= form_for @book do |f| %>
                <div class="title">
                    <%= f.label :タイトル %>
                    <%= f.text_field :title, :size => 40 %>
                </div>
                <div class="price">
                    <%= f.label :価格 %>
                    <%= f.number_field :price, :size => 30 %>
                </div>
                <div class="classroom">
                    <%= f.label :授業 %>
                    <%= f.text_field :classroom, :size => 50 %>
                </div>
                <div class="writer">
                    <%= f.label :作者 %>
                    <%= f.text_field :writer, :size => 50 %>
                </div>
                <div class="image">
                    <%= f.label :画像 %>
                    <%= f.file_field :image %>
                </div>
                <div class="comment">
                    <%= f.label :出品物の状態など %>
                    <%= f.text_area :comment %>
                </div>
            <%= f.submit "出品する" %>
        <% end %>
    </div>

app/views/books/index.html.erb
<%= stylesheet_link_tag "index", :media => "all" %>
<div class="container">
    <h1>書籍一覧</h1>
    <%= form_tag({controller:"books",action:"index"}, method: :get) do %>
        <div class="indexTag">
            <%= text_field_tag :search %>
            <button type="submit">
                <h2><i class="fas fa-search"></i></h2>
            </button>
        </div>
    <% end %>
    <%= page_entries_info @books %>
    <hr>
    <div class="books-container">
        <% @books.each do |t| %>
            <div class="book">
                <%= link_to(book_path(t.id)) do %>
                    <div class="book-photo">
                        <%=image_tag t.image_url, size:"200×250" if t.image? %>
                        <p>￥<%= t.price %></p>
                    </div>
                    <div class="book-info">
                        『<%= t.title %>』　<%= t.classroom %>
                    </div>
                <% end %>
            </div>
            <%= paginate @books %>
        <% end %>
    </div>
</div>

app/views/books/new.html.erb
<%= stylesheet_link_tag "books_new", :media => "all" %>
<div class="sell-container">
    <h1>出品ページ</h1>
    <%= form_for @book do |f| %>
        <div class="field">
            <%= f.label :タイトル %>
            <%= f.text_field :title, :size => 40 %>
        </div>
        <div class="field">
            <%= f.label :価格 %>
            <%= f.number_field :price, :size => 30 %>
        </div>
        <div class="field">
            <%= f.label :授業 %>
            <%= f.text_field :classroom, :size => 50 %>
        </div>
        <div class="field">
            <%= f.label :作者 %>
            <%= f.text_field :writer, :size => 50 %>
        </div>
        <div class="field">
            <%= f.label :画像 %>
            <%= f.file_field :image %>
        </div>
        <div class="field">
            <%= f.label :出品物の状態など %>
            <%= f.text_area :comment %>
        </div>
        <%= f.submit "出品する" %>
    <% end %>
</div>

app/views/books/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<div class="info">
  <div class="title">
    <h1>書籍詳細</h1>
  </div>
  <div class="center">
    <div class="left">
      <p><%= image_tag @book.image_url, size: "300×240" %></p>
    </div>
    <div class="right">
      <table>
        <tr><td><h2>出品者</td><td><a href="/users/<%= @book.user.id %>"><%= @book.user.name %></a></h2></td></tr>
        <tr><td><h2>題名</td><td>『<%= @book.title %>』</h2></td></tr>
        <tr><td><h2>価格</td><td><%= @book.price %>円</h2></td></tr>
        <tr><td><h2>授業</td><td><%= @book.classroom %></h2></td></tr>
        <tr><td><h2>投稿日</td><td><%= @book.created_at %></h2></td></tr>
        <tr><td><h2>コメント</td><td><%= @book.comment %></h2></td></tr>
      </table>
    </div>
  </div>
  <div class="button">
    <% if user_signed_in? && current_user.id == @book.user_id %>
      <div class="editDeleteButton">
        <%= link_to(edit_book_path) do %>
          <h2><i class="fas fa-pen"></i></h2>
        <% end %>   
        <%= link_to(book_path, method: :delete) do %>
          <h2><i class="fas fa-trash"></i></h2>
        <% end %> 
      </div>
    <% else %>
      <h3>購入ボタン: <%= @book.likes.count %></h3>
      <% if current_user.already_liked?(@book) %>
        <h2>'購入申請済み'</h2> 
      <% else %>
        <%= button_to '購入申請をする', book_likes_path(@book) %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="comment-wrapper">
  <div class="title">
    <h2>コメント一覧</h2>
  </div>
  <div class="comment">
    <hr>
    <% @comments.each do |c| %>
      <div>
        <%= c.user.name unless c.user.blank? %>：<%= c.comment %>
      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= form_with(model: [@book, @comment], local: true) do |f| %>
        <%= f.text_area :comment%>
        <%= button_tag type: "submit" do %>
          <i class="far fa-comments"></i> コメントする
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>