config/routes.rb
Rails.application.routes.draw do
  get 'top/index'
  get 'top/show'
  get 'users/show'
  devise_for :users
  resources :books do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  root 'books#index'
  patch 'notifications/admit' => 'rooms#admit' ,as:'room_admit'
  get 'notifications/deny'
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :notifications, only: [:index, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    default_scope -> { order(created_at: :desc) }
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @currentEntries = current_user.entries
    myRoomIds = []
    @currentEntries.each do | entry |
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id)
  end
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="chat">
  <h1>DM一覧</h1>
  <h6>チャットをする人を選んでください</h6>
  <hr>
  <% @anotherEntries.each do |e| %>
    <%= link_to (room_path(e.room.id)) do %>
      <div class="chatBox">
        <div class="chatBoxImage">
          <%= image_tag e.user.image_url, size:"100×100" if e.user.image? %>
        </div>
        <div class="chatBoxContent">
          <h4><%= e.user.name %></h4>
          </br>
          <h3><%= Message.find_by(id: e.room.message_ids.last).content %></h3>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/rooms/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<div class="left-button">
  <%= link_to "DM一覧に戻る", rooms_path %>
</div>
<h4 class="rooms-title">売買の場所・日時を二人で決めてください。</h4>
<% @entries.each do |e| %>
  <div class="user-name">
    <strong>
        <a class="rooms-user-link" href="/users/<%= e.user.id %>"><%= e.user.name %>さん</a>
    </strong>
  </div>
<% end %>
<hr>
<div class="chats">
  <h1>個人DMページ</h1>
  <hr>
  <div class="chat">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <div class="chat-box">
            <div class="chat-name">
                <%= m.user.name %>：
            </div>
            <div class="chat-hukidashi"> <strong><%= m.content %></strong> <br>
                <h6><%= m.created_at %></h6>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <hr>
  <div class="posts">
    <%= form_for @message do |f| %>
      <%= f.text_field :content, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
          <%= f.submit "送信",class: 'form-submit'%>
    <% end %>
  </div>
</div>